/*
** EPITECH PROJECT, 2023
** ftrace
** File description:
** error.h
*/

#pragma once

#include <signal.h>
#include <unistd.h>

#define SIGNAL_ENTRY(code) [code] = #code

static const char *signal_names[] = {
    [0] = NULL,
    SIGNAL_ENTRY(SIGABRT),
    SIGNAL_ENTRY(SIGALRM),
    SIGNAL_ENTRY(SIGBUS),
    SIGNAL_ENTRY(SIGCHLD),
    SIGNAL_ENTRY(SIGCONT),
    SIGNAL_ENTRY(SIGFPE),
    SIGNAL_ENTRY(SIGHUP),
    SIGNAL_ENTRY(SIGILL),
    SIGNAL_ENTRY(SIGINT),
    SIGNAL_ENTRY(SIGKILL),
    SIGNAL_ENTRY(SIGPIPE),
    SIGNAL_ENTRY(SIGQUIT),
    SIGNAL_ENTRY(SIGSEGV),
    SIGNAL_ENTRY(SIGSTOP),
    SIGNAL_ENTRY(SIGTERM),
    SIGNAL_ENTRY(SIGTSTP),
    SIGNAL_ENTRY(SIGTTIN),
    SIGNAL_ENTRY(SIGTTOU),
    SIGNAL_ENTRY(SIGUSR1),
    SIGNAL_ENTRY(SIGUSR2),
    SIGNAL_ENTRY(SIGPOLL),
    SIGNAL_ENTRY(SIGPROF),
    SIGNAL_ENTRY(SIGSYS),
    SIGNAL_ENTRY(SIGTRAP),
    SIGNAL_ENTRY(SIGURG),
    SIGNAL_ENTRY(SIGVTALRM),
    SIGNAL_ENTRY(SIGXCPU),
    SIGNAL_ENTRY(SIGXFSZ),
    SIGNAL_ENTRY(SIGWINCH),
    SIGNAL_ENTRY(SIGPWR),
};

#define SIGNAL_NB (sizeof(signal_names) / sizeof(char *))
